# GTFS RT

All the vehicle locations for vehicles in a geographical location can be obtained using the get_gtfs_rt_data_feed method with a bounding box.

In [1]:
from bods_client.client import BODSClient
from bods_client.models import BoundingBox, GTFSRTParams
from bods_client.models import Siri, SIRIVMParams, TimetableParams
import pandas as pd

In [2]:
API_KEY = "971a1adef42c46be54c3f898dec561eb24aad3a1"
bods = BODSClient(api_key=API_KEY)

# Get GTFS RT data by operator ref

In [3]:
result = pd.DataFrame()

In [7]:
def get_bods(operator):
    operator_refs = [operator]
    params = SIRIVMParams(operator_refs=operator_refs)
    siri_response = bods.get_siri_vm_data_feed(params=params)
    siri = Siri.from_bytes(siri_response)
    #print(siri)
    vehicle_activities = siri.service_delivery.vehicle_monitoring_delivery.vehicle_activities
    
    df = pd.DataFrame([t.__dict__ for t in vehicle_activities ])
    df = df.drop('monitored_vehicle_journey', axis=1)
    
    df2 = pd.DataFrame([t.monitored_vehicle_journey.__dict__ for t in vehicle_activities ])
    df2 = df2.drop('vehicle_location', axis=1)
    
    df3 = pd.DataFrame([t.monitored_vehicle_journey.vehicle_location.__dict__ for t in vehicle_activities ])
    
    return pd.concat([df, df2, df3], axis=1)

In [90]:
result_prev = result.copy()

In [124]:
result = get_bods("TFLO")

In [125]:
result['recorded_at_time'].max()

Timestamp('2023-05-10 10:06:52+0000', tz='UTC')

In [68]:
len(result.published_line_name.unique())

547

In [57]:
import numpy as np
list_lines = np.sort(result.published_line_name.unique())[:100].tolist()

In [58]:
list_lines

['1',
 '100',
 '101',
 '102',
 '103',
 '104',
 '105',
 '106',
 '107',
 '108',
 '109',
 '11',
 '110',
 '111',
 '112',
 '113',
 '114',
 '115',
 '116',
 '117',
 '118',
 '119',
 '12',
 '120',
 '121',
 '122',
 '123',
 '124',
 '125',
 '126',
 '127',
 '128',
 '129',
 '13',
 '130',
 '131',
 '132',
 '133',
 '134',
 '135',
 '136',
 '137',
 '138',
 '139',
 '14',
 '140',
 '141',
 '142',
 '143',
 '144',
 '145',
 '146',
 '147',
 '148',
 '149',
 '15',
 '150',
 '151',
 '152',
 '153',
 '154',
 '155',
 '156',
 '157',
 '158',
 '159',
 '16',
 '160',
 '161',
 '162',
 '163',
 '164',
 '165',
 '166',
 '167',
 '168',
 '169',
 '17',
 '170',
 '171',
 '172',
 '173',
 '174',
 '175',
 '176',
 '177',
 '178',
 '179',
 '18',
 '180',
 '181',
 '182',
 '183',
 '184',
 '185',
 '186',
 '187',
 '188',
 '189',
 '19']

# Speed calculation

In [92]:
result_prev_155 = result_prev[(result_prev.published_line_name == "155")]\
[['vehicle_ref','vehicle_journey_ref','recorded_at_time','origin_ref','origin_name','published_line_name',\
  'destination_ref','destination_name','origin_aimed_departure_time','direction_ref','longitude','latitude']]

In [73]:
result_prev_155[(result_prev_155.direction_ref == "1")].sort_values(by=['vehicle_ref'])

,vehicle_ref,vehicle_journey_ref,recorded_at_time,origin_ref,origin_name,published_line_name,destination_ref,destination_name,origin_aimed_departure_time,direction_ref,longitude,latitude
1014,BD65EVX,235404,2023-05-09 12:32:44+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 11:49:00+00:00,1,-0.118436,51.476280
2511,BD65EVY,235371,2023-05-09 12:31:52+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 11:40:00+00:00,1,-0.101868,51.496185
215,BD65EWA,236409,2023-05-09 12:22:41+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 11:23:00+00:00,1,-0.118436,51.476280
5726,BD65EWO,235322,2023-05-09 12:32:30+00:00,490008918N,Lambeth Road,155,490009281C,Elephant & Castle / London Road,2023-05-09 12:18:00+00:00,1,-0.105898,51.498543
2512,BD65EWX,235433,2023-05-09 12:32:37+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 11:58:00+00:00,1,-0.137914,51.461914
1968,BF65WLH,235514,2023-05-09 12:32:35+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 12:23:00+00:00,1,-0.164109,51.431763
2515,LF67EXA,235493,2023-05-09 12:32:23+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 12:15:00+00:00,1,-0.153362,51.442951
858,LF67EXB,235456,2023-05-09 12:32:23+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 12:06:00+00:00,1,-0.149556,51.446838
2516,LF67EXD,235543,2023-05-09 12:32:32+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 12:31:00+00:00,1,-0.172841,51.423752
5727,YX18KWW,235343,2023-05-09 12:29:12+00:00,490008918N,Lambeth Road,155,490009281C,Elephant & Castle / London Road,2023-05-09 12:27:00+00:00,1,-0.107017,51.497482

In [122]:
result_155 = result[(result.published_line_name == "155")]\
[['vehicle_ref','vehicle_journey_ref','recorded_at_time','origin_ref','origin_name','published_line_name',\
  'destination_ref','destination_name','origin_aimed_departure_time','direction_ref','longitude','latitude']]

In [123]:
result_155[(result_155.direction_ref == "1")].sort_values(by=['vehicle_ref'])

,vehicle_ref,vehicle_journey_ref,recorded_at_time,origin_ref,origin_name,published_line_name,destination_ref,destination_name,origin_aimed_departure_time,direction_ref,longitude,latitude
1074,BD65EVX,235417,2023-05-09 20:15:16+00:00,490008918N,Lambeth Road,155,None,Stockwell,2023-05-09 19:43:00+00:00,1,-0.124033,51.474281
2570,BD65EVY,235387,2023-05-09 21:10:32+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 20:45:00+00:00,1,-0.130078,51.465210
219,BD65EWA,236409,2023-05-09 12:22:41+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 11:23:00+00:00,1,-0.118436,51.476280
6409,BD65EWV,235151,2023-05-09 18:21:52+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 17:33:00+00:00,1,-0.104107,51.498070
2027,BF65WLH,235530,2023-05-09 21:10:30+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 21:09:00+00:00,1,-0.171945,51.424107
2571,BT65JGU,235278,2023-05-09 21:05:55+00:00,490008918N,Lambeth Road,155,490009281C,Elephant & Castle / London Road,2023-05-09 21:01:00+00:00,1,-0.106346,51.497719
2572,LF67EXA,235502,2023-05-09 17:55:21+00:00,490008918N,Lambeth Road,155,None,Stockwell,2023-05-09 17:55:00+00:00,1,-0.111047,51.493832
919,LF67EXB,235472,2023-05-09 21:10:34+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 20:57:00+00:00,1,-0.147989,51.449665
2577,LF67EXE,235307,2023-05-09 19:27:57+00:00,490008918N,Lambeth Road,155,None,Stockwell,2023-05-09 19:07:00+00:00,1,-0.124257,51.474281
6380,YX18KXA,235619,2023-05-09 21:10:27+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 20:33:00+00:00,1,-0.106569,51.487823

In [105]:
output = result_155.merge(result_prev_155,\
                          on=['vehicle_ref','direction_ref','vehicle_journey_ref','published_line_name'],\
                          how='left')

In [106]:
output['delta_time_sec'] = (pd.to_datetime(output.recorded_at_time_x) -\
                    pd.to_datetime(output.recorded_at_time_y)).dt.total_seconds()
output['delta_time_sec'] = output['delta_time_sec'].fillna(0)

In [107]:
import haversine as hs
def calc_distance(lon_x, lat_x, lon_y, lat_y):
    loc1=(lon_x,lat_x)
    loc2=(lon_y,lat_y)
    return hs.haversine(loc1,loc2)

In [108]:
output['distance_km'] = \
    output.apply(lambda x: calc_distance(x.longitude_x,x.latitude_x,x.longitude_y,x.latitude_y), axis=1)
output['distance_km'] = output['distance_km'].fillna(0)

In [109]:
output['avg_speed'] = output["distance_km"].divide((output["delta_time_sec"]/(60*60)), fill_value=0)

In [113]:
output['avg_speed'] = output['avg_speed'].fillna(-1)
output[['vehicle_ref','delta_time_sec','distance_km','avg_speed']]

   vehicle_ref  delta_time_sec  distance_km  avg_speed
0      BD65EWV             0.0     0.000000  -1.000000
1      BD65EWA             0.0     0.000000  -1.000000
2      LF67EXB           735.0     3.321420  16.268181
3      BD65EVX             0.0     0.000000  -1.000000
4      BD65EVR           690.0     2.377262  12.403108
5      BD65EVT           792.0     2.896409  13.165493
6      BF65WLH           583.0     2.569778  15.868270
7      BD65EVP             0.0     0.000000  -1.000000
8      BD65EVW             0.0     0.000000  -1.000000
9      BD65EVY           796.0     0.278685   1.260385
10     BD65EWX           731.0     2.526913  12.444442
11     BT65JGU           762.0     2.608046  12.321476
12     LF67EXA           780.0     3.040811  14.034512
13     LF67EXD           719.0     2.484013  12.437340
14     LF67EXE           744.0     2.243250  10.854437
15     BD65EWO           775.0     2.793737  12.977358
16     YX18KWW             0.0     0.000000  -1.000000

In [103]:
result_155 = result_155.merge(output[['vehicle_ref','delta_time_sec','distance_km','avg_speed']],\
                      on=['vehicle_ref'], how='left')

In [104]:
result_155

,vehicle_ref,vehicle_journey_ref,recorded_at_time,origin_ref,origin_name,published_line_name,destination_ref,destination_name,origin_aimed_departure_time,direction_ref,longitude,latitude,delta_time_sec,distance_km,avg_speed
0,BD65EWV,235143,2023-05-09 12:48:32+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 12:47:00+00:00,1,-0.174856,51.424461,NaN,NaN,NaN
1,BD65EWA,236409,2023-05-09 12:22:41+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 11:23:00+00:00,1,-0.118436,51.476280,0.0,0.000000,NaN
2,LF67EXB,235456,2023-05-09 12:49:10+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 12:06:00+00:00,1,-0.121794,51.473103,735.0,3.321420,16.268181
3,BD65EVX,235405,2023-05-09 12:46:07+00:00,490008918N,Lambeth Road,155,490009281C,Elephant & Castle / London Road,2023-05-09 12:44:00+00:00,1,-0.107017,51.497482,NaN,NaN,NaN
4,BD65EVR,235193,2023-05-09 12:48:24+00:00,490009281C,Elephant & Castle / London Road,155,490004076E,Blackshaw Road,2023-05-09 11:59:00+00:00,2,-0.157616,51.437061,690.0,2.377262,12.403108
5,BD65EVT,235228,2023-05-09 12:49:17+00:00,490009281C,Elephant & Castle / London Road,155,490004076E,Blackshaw Road,2023-05-09 12:08:00+00:00,2,-0.150676,51.445778,792.0,2.896409,13.165493
6,BF65WLH,235514,2023-05-09 12:46:30+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 12:23:00+00:00,1,-0.143511,51.457203,583.0,2.569778,15.868270
7,BD65EVP,235165,2023-05-09 12:49:03+00:00,490004076E,Blackshaw Road,155,490012696E,St George s Hospital,2023-05-09 12:46:00+00:00,2,-0.176647,51.424931,NaN,NaN,NaN
8,BD65EVW,235578,2023-05-09 12:48:27+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 12:39:00+00:00,1,-0.167467,51.428581,NaN,NaN,NaN
9,BD65EVY,235372,2023-05-09 12:48:57+00:00,490008918N,Lambeth Road,155,490009281C,Elephant & Castle / London Road,2023-05-09 12:35:00+00:00,1,-0.104107,51.498070,796.0,0.278685,1.260385
10,BD65EWX,235433,2023-05-09 12:49:06+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 11:58:00+00:00,1,-0.111047,51.483349,731.0,2.526913,12.444442
11,BT65JGU,235263,2023-05-09 12:48:50+00:00,490009281C,Elephant & Castle / London Road,155,490004076E,Blackshaw Road,2023-05-09 12:16:00+00:00,2,-0.147765,51.452610,762.0,2.608046,12.321476
12,LF67EXA,235493,2023-05-09 12:49:06+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 12:15:00+00:00,1,-0.132093,51.464149,780.0,3.040811,14.034512
13,LF67EXD,235543,2023-05-09 12:48:31+00:00,490012696E,St George s Hospital,155,490008918N,Lambeth Road,2023-05-09 12:31:00+00:00,1,-0.151795,51.444836,719.0,2.484013,12.437340
14,LF67EXE,235296,2023-05-09 12:49:03+00:00,490009281C,Elephant & Castle / London Road,155,490004076E,Blackshaw Road,2023-05-09 12:25:00+00:00,2,-0.136347,51.462502,744.0,2.243250,10.854437
15,BD65EWO,235323,2023-05-09 12:49:09+00:00,490009281C,Elephant & Castle / London Road,155,490004076E,Blackshaw Road,2023-05-09 12:34:00+00:00,2,-0.117764,51.476871,775.0,2.793737,12.977358
16,YX18KWW,235344,2023-05-09 12:48:58+00:00,490009281C,Elephant & Castle / London Road,155,490004076E,Blackshaw Road,2023-05-09 12:42:00+00:00,2,-0.107465,51.486881,NaN,NaN,NaN

# Simulation for social media analysis

In [61]:
path = "/Users/I559573/Downloads/itm_london_gtfs/stops.txt"
df_stops = pd.read_csv(path)

In [62]:
df_stops

,stop_id,stop_code,stop_name,stop_lat,stop_lon,wheelchair_boarding,location_type,parent_station,platform_code
0,0100BRP90233,bstdmgp,Triangle West,51.456524,-2.608023,0,NaN,NaN,NaN
1,0100BRP90237,bstdmwa,Queen's Road,51.456512,-2.606583,0,NaN,NaN,NaN
2,0100BRP90986,bstdatw,Black Boy Hill,51.471226,-2.616037,0,NaN,NaN,NaN
3,0100BRP90988,bstdgda,Black Boy Hill,51.470692,-2.615152,0,NaN,NaN,NaN
4,0100BRP90990,bstdmam,Clifton Down Station,51.464085,-2.609434,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
25072,940GZZLUWJN,NaN,Willesden Junction,51.532257,-0.244259,1,1.0,NaN,NaN
25073,940GZZLUWPL,NaN,Whitechapel,51.519516,-0.059945,2,1.0,NaN,NaN
25074,940GZZLUWRP,NaN,West Ruislip,51.569687,-0.437865,2,1.0,NaN,NaN
25075,940GZZLUWWL,NaN,Walthamstow Central,51.582966,-0.019858,2,1.0,NaN,NaN
25076,940GZZLUWYC,NaN,Wembley Central,51.552303,-0.296829,1,1.0,NaN,NaN

In [44]:
import urllib.request, json
import pandas as pd
from datetime import date
import random
from itertools import islice,cycle

def get_line_stops(line, direction):
    today = date.today()
    #print("Today's date:", today)

    df_line_stops = pd.DataFrame()

    url = "https://api.tfl.gov.uk/Line/"+line+"/Route/Sequence/"+direction+\
        "?serviceTypes=Regular&excludeCrowding=True"

    hdr ={
        # Request headers
        'Cache-Control': 'no-cache',
    }

    req = urllib.request.Request(url, headers=hdr)
    req.get_method = lambda: 'GET'
    response = urllib.request.urlopen(req)
    #print(response.getcode())
    #print(response.read())
    resp = json.loads(response.read())
        
    df_line_stops = pd.json_normalize(resp)
    #print(df_line_stops)
    line_stops = (df_line_stops.orderedLineRoutes.to_list())[0][0]['naptanIds']

    return line_stops

In [45]:
import uuid
from faker import Faker
import datetime as dt
import random
import uuid

def assign_event(date, df_line_stops_coord):    
    #list_sentiments = ['negative','neutral','positive']
    list_event_types = ['Road work','Public demonstration','Sport event','Incident','Festival/Concert','Fair']
    #random_sentiment = random.choices(list_sentiments, weights=(10,40,50), k=1)
    weights_ = (20,20,20,20,20,20)
    if bool(len(pd.bdate_range(date, date))):
        weights_ = (30,10,10,30,10,10)
    else:
        weights_ = (0,20,20,30,20,10)
    
    random_event = random.choices(list_event_types, weights=weights_, k=1)
    #print(random_event)
    
    start_idx = random.choices(df_line_stops_coord.index.values.tolist())
    step = num1 = random.randint(1, 3)
    end_idx = 0
    if (start_idx[0]+step) < len(df_line_stops_coord.index.values.tolist()):
        end_idx = start_idx[0]+step
    else:
        end_idx = start_idx[0]
    #print(start_idx, step, end_idx)

    df_stops_event = df_line_stops_coord.iloc[range(start_idx[0],end_idx)].copy()
    df_stops_event['event_category'] = random_event[0]

    #print(df_stops_event[['stop_id','stop_lat','stop_lon','event_category']])
    
    return df_stops_event[['stop_id','stop_lat','stop_lon','event_category']]

In [46]:
from randomtimestamp import randomtimestamp, random_date, random_time
from datetime import time

def event_time(report_date, event_category):    
    time_ = time(0, 0, 0)
    if event_category == 'Road work':
        time_ = random_time(start=time(7, 0, 0), end = time(17, 0, 0))
    elif event_category == 'Public demonstration':
        time_ = random_time(start=time(8, 0, 0), end = time(20, 0, 0))
    elif event_category == 'Sport event':
        time_ = random_time(start=time(9, 0, 0), end = time(23, 0, 0))
    elif event_category == 'Incident':
        time_ = random_time()
    elif event_category == 'Festival/Concert':
        time_ = random_time(start=time(18, 0, 0), end = time(23, 0, 0))
    elif event_category == 'Fair':
        time_ = random_time(start=time(7, 0, 0), end = time(17, 0, 0))
    
    mydatetime = dt.datetime.combine(report_date, time_)
    #print(mydatetime)
    return mydatetime

In [47]:
def simulate_data(report_date, line, direction, stop_lat, stop_lon, event_category):

    report_datetime = event_time(report_date, event_category)
    #print(report_datetime)

    rand_lat = random.gauss(stop_lat, 0.001)
    rand_lon = random.gauss(stop_lon, 0.001)
    
    #fake = Faker()
    #start_date = datetime.date(year=2023, month=1, day=1)
    #event_date = fake.date_time_between(start_date=start_date, end_date='now')
    #limit_date = event_date+dt.timedelta(days=7)
    #report_date = fake.date_time_between(start_date=event_date, end_date=limit_date)
    user_id = uuid.uuid4()
    
    #print(user_id, ",", report_date, ",", line, ",", event_category,\
    #      ",", rand_lat, ",", rand_lon)
    
    return {"id":user_id, "report_date":report_date, "report_datetime": report_datetime,\
            "published_line_name":line, "event_category":event_category,\
            "rec_lat":rand_lat, "rec_lon":rand_lon,\
            "orig_stop_lat":stop_lat, "orig_stop_lon":stop_lon}

In [48]:
df_simul = pd.DataFrame(columns=["id","report_date","report_datetime","published_line_name",\
                                 "event_category","rec_lat","rec_lon","orig_stop_lat","orig_stop_lon"])

In [63]:
import pandas as pd
from datetime import datetime

datelist = pd.date_range(start="2023-01-01", end=datetime.today())

for line in list_lines:
#for line in ["155"]:
    print(line)
    direction = "inbound"
    #print(line, direction)
    list_line_stops = get_line_stops(line, direction)
    #print(list_line_stops)
    df_line_stops = pd.DataFrame(list_line_stops, columns = ['stop_id'])
    #print(df_line_stops)
    df_line_stops_coord = df_line_stops.merge(df_stops, on='stop_id', how='left')
    for date in datelist:
        destiny = random.choices(['event','none'], weights=(30,70), k=1)
        #print(line, direction, date, destiny[0])
        if(destiny[0] == 'event'):
            df_stops_event = assign_event(date, df_line_stops_coord)
            #print(line, direction, date, destiny[0],df_stops_event[['event_category']].iloc[0])
            #print(df_stops_event[['stop_id','stop_lat','stop_lon','event_category']])
            for index, row in df_stops_event.iterrows():
                num = random.choices([10,20,30])
                for i in range(0,num[0]):
                    new_row = pd.DataFrame(simulate_data(date, line, direction,\
                                row.stop_lat, row.stop_lon, row.event_category), index=[0])
                    df_simul = pd.concat([new_row,df_simul.loc[:]]).reset_index(drop=True)

1
100
101
102
103
104
105
106
107
108
109
11
110
111
112
113
114
115
116
117
118
119
12
120
121
122
123
124
125
126
127
128
129
13
130
131
132
133
134
135
136
137
138
139
14
140
141
142
143
144
145
146
147
148
149
15
150
151
152
153
154
155
156
157
158
159
16
160
161
162
163
164
165
166
167
168
169
17
170
171
172
173
174
175
176
177
178
179
18
180
181
182
183
184
185
186
187
188
189
19

In [64]:
df_simul.count

<bound method DataFrame.count of                                           id report_date     report_datetime  \
0       4867e796-eac8-420a-b151-8936b3d23d33  2023-05-07 2023-05-07 22:42:25
1       6c6952d5-598a-46b1-9180-f48c85472a15  2023-05-07 2023-05-07 18:48:04
2       2948a188-84ea-4f63-9229-81f15c438b3b  2023-05-07 2023-05-07 19:45:51
3       9c6924ee-b43c-47f1-9312-0b0d57a9bfa7  2023-05-07 2023-05-07 19:18:51
4       219249f9-3ab5-4956-9444-7b5aad09cc06  2023-05-07 2023-05-07 18:31:08
...                                      ...         ...                 ...
146775  573dd7c3-47f8-47e9-90ab-3503f2abc2f8  2023-01-02 2023-01-02 09:53:36
146776  86547653-4106-49c4-b1d4-5bdc3ba8a9a9  2023-01-02 2023-01-02 16:14:25
146777  ba8589eb-d0c2-47aa-90cf-02b02109ca1c  2023-01-02 2023-01-02 16:48:03
146778  d485c831-61ce-4fda-9e95-432b5f6d7802  2023-01-02 2023-01-02 22:40:21
146779  da127112-4c9d-4203-83ff-472c9c583a04  2023-01-02 2023-01-02 22:13:07

       published_line_name    event_category    rec_lat   rec_lon  \
0                       19  Festival/Concert  51.507355 -0.142508
1                       19  Festival/Concert  51.507274 -0.143664
2                       19  Festival/Concert  51.507837 -0.140572
3                       19  Festival/Concert  51.507240 -0.142483
4                       19  Festival/Concert  51.506691 -0.142431
...                    ...               ...        ...       ...
146775                   1       Sport event  51.491998 -0.064384
146776                   1       Sport event  51.490983 -0.063887
146777                   1       Sport event  51.492590 -0.063318
146778                   1       Sport event  51.493186 -0.064353
146779                   1       Sport event  51.491905 -0.063173

        orig_stop_lat  orig_stop_lon
0           51.507015      -0.142529
1           51.507015      -0.142529
2           51.507015      -0.142529
3           51.507015      -0.142529
4           51.507015      -0.142529
...               ...            ...
146775      51.492252      -0.064848
146776      51.492252      -0.064848
146777      51.492252      -0.064848
146778      51.492252      -0.064848
146779      51.492252      -0.064848

[146780 rows x 9 columns]>

In [65]:
df_simul.to_csv('simulation_social_media.csv', index=False)

In [ ]:
df_groupby = df_simul.groupby(['report_date','event_category'])['id'].agg('count').reset_index()

In [ ]:
df_groupby

In [ ]:
df_groupby.to_csv('simul_groupby.csv', index=False)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
g = sns.lineplot(data=df_groupby, x="report_date", y="id", hue="event_category")
plt.xticks(rotation=45)

# Bus Timing

In [ ]:
vehicle_ref = "BD65EVM"

########### Python 3.2 #############
import urllib.request, json
df_vehicle_timing = pd.DataFrame()
try:
    url = "https://api.tfl.gov.uk/Vehicle/"+vehicle_ref+"/Arrivals"

    hdr ={
    # Request headers
    'Cache-Control': 'no-cache',
    }

    req = urllib.request.Request(url, headers=hdr)

    req.get_method = lambda: 'GET'
    response = urllib.request.urlopen(req)
    print(response.getcode())
    #print(response.read())
    resp = json.loads(response.read())
    df_vehicle_timing = pd.json_normalize(resp)
    df_vehicle_timing["load_date"] = today

except Exception as e:
    print(e)
####################################

In [ ]:
df_vehicle_timing.rename(columns = {'timing.$type':'timing_type'}, inplace = True)

In [ ]:
df_vehicle_timing[['id', 'vehicleId', 'naptanId', 'stationName',
       'lineId', 'lineName', 'platformName', 'direction',
       'destinationNaptanId', 'destinationName', 'timestamp', 'timeToStation',
       'currentLocation', 'towards', 'expectedArrival', 'timeToLive',
       'modeName', 'load_date']]

# Service issue

In [ ]:
path = "/Users/I559573/Downloads/itm_london_gtfs/calendar.txt"
df_calendar = pd.read_csv(path)

In [ ]:
df_calendar

In [ ]:
import calendar
from datetime import date

today = today = date.today()
day_name = today.strftime('%A')

In [ ]:
from pandasql import sqldf

In [ ]:
q = "SELECT * FROM df_calendar WHERE "+day_name+" = '1'"
print(q)
sqldf(q, globals())

In [ ]:
q = "WITH xxx AS (SELECT service_id, "+\
" CASE WHEN monday = 1 THEN 'monday' "+\
" END monday_1, "+\
" CASE WHEN tuesday = 1 THEN 'tuesday' "+\
" END tuesday_1, "+\
" CASE WHEN wednesday = 1 THEN 'wednesday' "+\
" END wednesday_1, "+\
" CASE WHEN thursday = 1 THEN 'thursday' "+\
" END thursday_1, "+\
" CASE WHEN friday = 1 THEN 'friday' "+\
" END friday_1, "+\
" CASE WHEN saturday = 1 THEN 'saturday' "+\
" END saturday_1, "+\
" CASE WHEN sunday = 1 THEN 'sunday' "+\
" END sunday_1, "+\
" start_date, end_date FROM df_calendar)"+\
" SELECT "+\
" monday_1||','||xxx.service_id||','||xxx.service_id sequence "+\
" FROM xxx "
print(q)
sqldf(q, globals())

# Visualization

## Bus locations

In [ ]:
import folium

this_map = folium.Map(location=[51.5, -0.12], zoom_start=12
                      #,TileLayer='openstreetmap'
                     )

folium.TileLayer('Stamen Terrain').add_to(this_map)
folium.TileLayer('Stamen Toner').add_to(this_map)
folium.TileLayer('Stamen Water Color').add_to(this_map)
folium.TileLayer('cartodbpositron').add_to(this_map)
folium.TileLayer('cartodbdark_matter').add_to(this_map)
folium.LayerControl().add_to(this_map)

In [ ]:
def getRGBfromI(RGBint):
    RGBint = RGBint*RGBint*RGBint
    blue  =  RGBint & 255
    green = (RGBint >> 8) & 255
    red   =   (RGBint >> 16) & 255
    return red, green, blue

In [ ]:
def rgb_to_hex(rgb):
    return '#%02x%02x%02x' % rgb

In [ ]:
sel_line_num = "155"

In [ ]:
result[result["published_line_name"]==sel_line_num]
result['color'] = (result['line_ref'].astype(int)).apply(getRGBfromI)
result['color'] = result['color'].apply(rgb_to_hex)
result["current_timestamp"] = pd.Timestamp('now')

In [ ]:
result[result["published_line_name"]==sel_line_num]

In [ ]:
result.to_csv("save.csv",index=False)

In [ ]:
def plotDot(point):
    '''input: series that contains a numeric named latitude and a numeric named longitude
    this function creates a CircleMarker and adds it to your this_map'''
    folium.CircleMarker(
                        location=[point.latitude, point.longitude],
                        popup="<i>Operator:"+point.operator_ref+", Vehicle: "+point.vehicle_ref+\
                            ", Line: "+point.published_line_name+"</i>", 
                        tooltip="Click me!",
                        radius=3,
                        fill=True,
                        fill_color=point.color,
                        color=point.color,
                        weight=5/int(point.direction_ref)
                       ).add_to(this_map)

In [ ]:
data = result[['operator_ref','vehicle_ref','published_line_name','line_ref','direction_ref',\
               'latitude','longitude','color']]
data = data[data.published_line_name == sel_line_num]
data.apply(plotDot, axis = 1)

## Road disruptions

In [20]:
import urllib.request, json
import pandas as pd
from datetime import date

today = date.today()
print("Today's date:", today)

df_disruptions = pd.DataFrame()
try:
    url = "https://api.tfl.gov.uk/Road/all/Street/Disruption?startDate="+str(today)+"&endDate="+str(today)

    hdr ={
    # Request headers
    'Cache-Control': 'no-cache',
    }

    req = urllib.request.Request(url, headers=hdr)

    req.get_method = lambda: 'GET'
    response = urllib.request.urlopen(req)
    #print(response.getcode())
    #print(response.read())
    resp = json.loads(response.read())
    df_disruptions = pd.json_normalize(resp)
    df_disruptions["load_date"] = today
except Exception as e:
    print(e)

Today's date: 2023-05-09

In [21]:
df_disruptions.closure.count()

134

In [23]:
df_disruptions

,$type,streetName,closure,directions,lineString,distruptedStreetId,disruptionId,startLat,startLon,endLat,...,severity,category,subCategory,comments,startDateTime,endDateTime,levelOfInterest,location,recurringSchedules,load_date
0,Tfl.Api.Presentation.Entities.DisruptedStreetS...,"[A200,A2209] CREEK ROAD (SE10;SE8,SE8,SE10)",Closed,Eastbound,"[[-0.013498,51.481445],[-0.011569,51.48144]]",TIMS-17496716748,TIMS-174967,51.481445,-0.013498,51.481440,...,Minimal,Works,Borough works,[A200] Creek Road (Eastbound) between Creeksid...,2023-04-03T06:00:00Z,2023-05-12T18:00:00Z,Medium,"[A200,A2209] CREEK ROAD (SE10;SE8,SE8,SE10) (G...",[],2023-05-09
1,Tfl.Api.Presentation.Entities.DisruptedStreetS...,"[A200,A2209] CREEK ROAD (SE10;SE8,SE8,SE10)",Closed,Eastbound,"[[-0.017031,51.481352],[-0.015088,51.481392]]",TIMS-17496716749,TIMS-174967,51.481352,-0.017031,51.481392,...,Minimal,Works,Borough works,[A200] Creek Road (Eastbound) between Creeksid...,2023-04-03T06:00:00Z,2023-05-12T18:00:00Z,Medium,"[A200,A2209] CREEK ROAD (SE10;SE8,SE8,SE10) (G...",[],2023-05-09
2,Tfl.Api.Presentation.Entities.DisruptedStreetS...,"[A200,A2209] CREEK ROAD (SE10;SE8,SE8,SE10)",Closed,Eastbound,"[[-0.020646,51.481009],[-0.022208,51.480855]]",TIMS-17496716750,TIMS-174967,51.481009,-0.020646,51.480855,...,Minimal,Works,Borough works,[A200] Creek Road (Eastbound) between Creeksid...,2023-04-03T06:00:00Z,2023-05-12T18:00:00Z,Medium,"[A200,A2209] CREEK ROAD (SE10;SE8,SE8,SE10) (G...",[],2023-05-09
3,Tfl.Api.Presentation.Entities.DisruptedStreetS...,"[A200,A2209] CREEK ROAD (SE10;SE8,SE8,SE10)",Closed,Eastbound,"[[-0.019709,51.481127],[-0.02056,51.481016]]",TIMS-17496716751,TIMS-174967,51.481127,-0.019709,51.481016,...,Minimal,Works,Borough works,[A200] Creek Road (Eastbound) between Creeksid...,2023-04-03T06:00:00Z,2023-05-12T18:00:00Z,Medium,"[A200,A2209] CREEK ROAD (SE10;SE8,SE8,SE10) (G...",[],2023-05-09
4,Tfl.Api.Presentation.Entities.DisruptedStreetS...,"[A200,A2209] CREEK ROAD (SE10;SE8,SE8,SE10)",Closed,Eastbound,"[[-0.017031,51.481352],[-0.018669,51.48124]]",TIMS-17496716752,TIMS-174967,51.481352,-0.017031,51.481240,...,Minimal,Works,Borough works,[A200] Creek Road (Eastbound) between Creeksid...,2023-04-03T06:00:00Z,2023-05-12T18:00:00Z,Medium,"[A200,A2209] CREEK ROAD (SE10;SE8,SE8,SE10) (G...",[],2023-05-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,Tfl.Api.Presentation.Entities.DisruptedStreetS...,"[A41] FINCHLEY ROAD (NW3,NW6,NW8)",Closed,Northbound,"[[-0.174974,51.541694],[-0.175204,51.542066]]",TIMS-17703517521,TIMS-177035,51.541694,-0.174974,51.542066,...,Serious,Works,Network Rail works,[A41] Finchley Road (Northbound) between [B509...,2023-05-08T23:01:00Z,2023-06-17T22:59:00Z,High,"[A41] FINCHLEY ROAD (NW3,NW6,NW8) (Camden,West...",[],2023-05-09
130,Tfl.Api.Presentation.Entities.DisruptedStreetS...,"[A41] FINCHLEY ROAD (NW3,NW6,NW8)",Closed,Northbound,"[[-0.175204,51.542066],[-0.175089,51.542887]]",TIMS-17703517522,TIMS-177035,51.542066,-0.175204,51.542887,...,Serious,Works,Network Rail works,[A41] Finchley Road (Northbound) between [B509...,2023-05-08T23:01:00Z,2023-06-17T22:59:00Z,High,"[A41] FINCHLEY ROAD (NW3,NW6,NW8) (Camden,West...",[],2023-05-09
131,Tfl.Api.Presentation.Entities.DisruptedStreetS...,"[A41] FINCHLEY ROAD (NW3,NW6,NW8)",Closed,Northbound,"[[-0.175089,51.543143],[-0.174694,51.543272]]",TIMS-17703517523,TIMS-177035,51.543143,-0.175089,51.543272,...,Serious,Works,Network Rail works,[A41] Finchley Road (Northbound) between [B509...,2023-05-08T23:01:00Z,2023-06-17T22:59:00Z,High,"[A41] FINCHLEY ROAD (NW3,NW6,NW8) (Camden,West...",[],2023-05-09
132,Tfl.Api.Presentation.Entities.DisruptedStreetS...,"[A41] FINCHLEY ROAD (NW3,NW6,NW8)",Closed,Northbound,"[[-0.175089,51.542887],[-0.175089,51.543143]]",TIMS-17703517524,TIMS-177035,51.542887,-0.175089,51.543143,...,Serious,Works,Network Rail works,[A41] Finchley Road (Northbound) between [B509...,2023-05-08T23:01:00Z,2023-06-17T22:59:00Z,High,"[A41] FINCHLEY ROAD (NW3,NW6,NW8) (Camden,West...",[],2023-05-09
133,Tfl.Api.Presentation.Entities.DisruptedStreetS...,"[A41] FINCHLEY ROAD (NW3,NW6,NW8)",Closed,Northbound,"[[-0.174694,51.543272],[-0.174483,51.543134]]",TIMS-17703517525,TIMS-177035,51.543272,-0.174694,51.543134,...,Serious,Works,Network Rail works,[A41] Finchley Road (Northbound) between [B509...,2023-05-08T23:01:00Z,2023-06-17T22:59:00Z,High,"[A41] FINCHLEY ROAD (NW3,NW6,NW8) (Camden,West...",[],2023-05-09

In [ ]:
df_disruptions = df_disruptions.drop(columns=['$type', 'recurringSchedules'])
df_disruptions.to_excel("df_disruptions_2.xlsx")

In [ ]:
def plotDot2(point):
    '''input: series that contains a numeric named latitude and a numeric named longitude
    this function creates a CircleMarker and adds it to your this_map'''
    folium.CircleMarker(
                        location=[point.startLat, point.startLon],
                        popup="<i> ID: "+point.disruptionId+",\n Street name:"+point.streetName+\
                            ",\n Closure: "+point.closure+\
                            ",\n Directions: "+point.directions+",\n Category: "+point.category+\
                            ",\n Subcategory: "+point.subCategory+",\n Severity: "+point.severity+"</i>", 
                        tooltip="Click me!",
                        radius=3,
                        fill=True,
                        fill_color="red",
                        color="red",
                        weight=5
                       ).add_to(this_map)
    folium.CircleMarker(
                        location=[point.endLat, point.endLon],
                        popup="<i> ID: "+point.disruptionId+",\n Street name:"+point.streetName+\
                            ",\n Closure: "+point.closure+\
                            ",\n Directions: "+point.directions+",\n Category: "+point.category+\
                            ",\n Subcategory: "+point.subCategory+",\n Severity: "+point.severity+"</i>", 
                        tooltip="Click me!",
                        radius=3,
                        fill=True,
                        fill_color="blue",
                        color="blue",
                        weight=5
                       ).add_to(this_map)
    folium.PolyLine([[point.startLat,point.startLon],[point.endLat,point.endLon]]
                        ,color="black", 
                        #weight=1.5, 
                        #opacity=0.8
                       ).add_to(this_map)

In [ ]:
df_disruptions.apply(plotDot2, axis = 1)

## Data from social media

In [ ]:
#[‘red’, ‘blue’, ‘green’, ‘purple’, ‘orange’, ‘darkred’,
#’lightred’, ‘beige’, ‘darkblue’, ‘darkgreen’, ‘cadetblue’, ‘darkpurple’, ‘white’, ‘pink’,\
# ‘lightblue’, ‘lightgreen’, ‘gray’, ‘black’, ‘lightgray’]

event_types = [
    (df_simul['event_category'] == "Road work"),
    (df_simul['event_category'] == "Public demonstration"),
    (df_simul['event_category'] == "Sport event"),
    (df_simul['event_category'] == "Incident"),
    (df_simul['event_category'] == "Festival/Concert"),
    (df_simul['event_category'] == "Fair")
]

values = ['green', 'blue', 'orange', 'purple', 'red', 'pink']

In [ ]:
import numpy as np
df_simul['color'] = np.select(event_types, values)

In [ ]:
df_simul

In [ ]:
def plotDot3(point):
    '''input: series that contains a numeric named latitude and a numeric named longitude
    this function creates a CircleMarker and adds it to your this_map'''
    folium.Circle(
                        location=[point.rec_lat, point.rec_lon],
                        popup="<i>Coord: ("+str(point.rec_lat)+","+str(point.rec_lon)+\
                            "), Date: "+str(point.report_datetime)+", Event category: "+point.event_category+\
                            ", Line: "+point.published_line_name+"</i>", 
                        tooltip="Click me!",
                        radius=4,
                        fill=False,
                        fill_color=point.color,
                        color=point.color,
                        weight=4
                       ).add_to(this_map)
    folium.CircleMarker(
                        location=[point.orig_stop_lat, point.orig_stop_lon],
                        #tooltip="Click me!",
                        radius=5,
                        fill=True,
                        fill_color="yellow",
                        color="yellow",
                        weight=5
                       ).add_to(this_map)

In [ ]:
df_simul.apply(plotDot3, axis = 1)

In [ ]:
this_map